CREATE TABLE IF NOT EXISTS nx_admin_operation_mutex (
    lock_key VARCHAR(64) PRIMARY KEY,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO nx_admin_operation_mutex (lock_key) VALUES ('G2_EXCHANGE_EXECUTION');
