-- Idempotent MySQL 8 forward migration; executed by the guarded startup migration runner.
SET @schema_name = DATABASE();
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_wallet' AND column_name='run_id'), 'SELECT 1', 'ALTER TABLE nx_funds_sandbox_wallet ADD COLUMN run_id VARCHAR(64) NOT NULL DEFAULT ''legacy-run'' AFTER id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_order' AND column_name='run_id'), 'SELECT 1', 'ALTER TABLE nx_funds_sandbox_order ADD COLUMN run_id VARCHAR(64) NOT NULL DEFAULT ''legacy-run'' AFTER id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_ledger' AND column_name='run_id'), 'SELECT 1', 'ALTER TABLE nx_funds_sandbox_ledger ADD COLUMN run_id VARCHAR(64) NOT NULL DEFAULT ''legacy-run'' AFTER id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_callback_inbox' AND column_name='run_id'), 'SELECT 1', 'ALTER TABLE nx_funds_sandbox_callback_inbox ADD COLUMN run_id VARCHAR(64) NOT NULL DEFAULT ''legacy-run'' AFTER id'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- The original global unique keys have to be removed, otherwise a Run B fixture
-- can collide with Run A. INFORMATION_SCHEMA guards make replay safe.
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_wallet' AND index_name='uk_funds_sandbox_wallet_user'), 'ALTER TABLE nx_funds_sandbox_wallet DROP INDEX uk_funds_sandbox_wallet_user', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_wallet' AND index_name='uk_funds_sandbox_wallet_run_user'), 'SELECT 1', 'ALTER TABLE nx_funds_sandbox_wallet ADD UNIQUE KEY uk_funds_sandbox_wallet_run_user (run_id,user_id)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_order' AND index_name='uk_funds_sandbox_order_no'), 'ALTER TABLE nx_funds_sandbox_order DROP INDEX uk_funds_sandbox_order_no', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_order' AND index_name='uk_funds_sandbox_order_idem'), 'ALTER TABLE nx_funds_sandbox_order DROP INDEX uk_funds_sandbox_order_idem', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_order' AND index_name='uk_funds_sandbox_order_run_no'), 'SELECT 1', 'ALTER TABLE nx_funds_sandbox_order ADD UNIQUE KEY uk_funds_sandbox_order_run_no (run_id,order_no)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_order' AND index_name='uk_funds_sandbox_order_run_idem'), 'SELECT 1', 'ALTER TABLE nx_funds_sandbox_order ADD UNIQUE KEY uk_funds_sandbox_order_run_idem (run_id,user_id,idempotency_key)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_ledger' AND index_name='uk_funds_sandbox_ledger_no'), 'ALTER TABLE nx_funds_sandbox_ledger DROP INDEX uk_funds_sandbox_ledger_no', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_ledger' AND index_name='uk_funds_sandbox_ledger_role'), 'ALTER TABLE nx_funds_sandbox_ledger DROP INDEX uk_funds_sandbox_ledger_role', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_ledger' AND index_name='uk_funds_sandbox_ledger_run_no'), 'SELECT 1', 'ALTER TABLE nx_funds_sandbox_ledger ADD UNIQUE KEY uk_funds_sandbox_ledger_run_no (run_id,ledger_no)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_ledger' AND index_name='uk_funds_sandbox_ledger_run_role'), 'SELECT 1', 'ALTER TABLE nx_funds_sandbox_ledger ADD UNIQUE KEY uk_funds_sandbox_ledger_run_role (run_id,order_no,entry_role)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_callback_inbox' AND index_name='uk_funds_sandbox_callback_event'), 'ALTER TABLE nx_funds_sandbox_callback_inbox DROP INDEX uk_funds_sandbox_callback_event', 'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_callback_inbox' AND index_name='uk_funds_sandbox_callback_run_event'), 'SELECT 1', 'ALTER TABLE nx_funds_sandbox_callback_inbox ADD UNIQUE KEY uk_funds_sandbox_callback_run_event (run_id,event_id)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_order' AND index_name='idx_funds_sandbox_order_run_user_time'), 'SELECT 1', 'CREATE INDEX idx_funds_sandbox_order_run_user_time ON nx_funds_sandbox_order(run_id,user_id,created_at)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_ledger' AND index_name='idx_funds_sandbox_ledger_run_user_time'), 'SELECT 1', 'CREATE INDEX idx_funds_sandbox_ledger_run_user_time ON nx_funds_sandbox_ledger(run_id,user_id,created_at)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = IF(EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@schema_name AND table_name='nx_funds_sandbox_callback_inbox' AND index_name='idx_funds_sandbox_callback_run_order'), 'SELECT 1', 'CREATE INDEX idx_funds_sandbox_callback_run_order ON nx_funds_sandbox_callback_inbox(run_id,order_no,received_at)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
