CREATE TABLE IF NOT EXISTS nx_vietqr_receipt_evidence (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  asset_id VARCHAR(64) NOT NULL,
  object_key VARCHAR(255) NOT NULL,
  purpose VARCHAR(64) NOT NULL,
  content_type VARCHAR(128) NOT NULL,
  size_bytes BIGINT NOT NULL,
  content_sha256 CHAR(64) NOT NULL,
  uploaded_by VARCHAR(128) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
  bound_resource_type VARCHAR(64) NULL,
  bound_resource_id VARCHAR(96) NULL,
  bound_by VARCHAR(128) NULL,
  bound_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_vietqr_receipt_evidence_asset (asset_id),
  UNIQUE KEY uk_vietqr_receipt_evidence_object (object_key),
  KEY idx_vietqr_receipt_evidence_status (purpose, status, created_at),
  KEY idx_vietqr_receipt_evidence_bound (bound_resource_type, bound_resource_id),
  CONSTRAINT chk_vietqr_receipt_evidence_status CHECK (status IN ('AVAILABLE', 'BOUND')),
  CONSTRAINT chk_vietqr_receipt_evidence_size CHECK (size_bytes > 0 AND size_bytes <= 10485760)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
