spring:
  application:
    name: nexion-team-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:nexion}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: "${MYSQL_PASSWORD:A123456789Z!@#}"
  config:
    import:
      - optional:nacos:nexion-common.yaml
      - optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: "${NACOS_PASSWORD:nacos}"
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        file-extension: yaml

server:
  port: 8106

nexion:
  gateway:
    internal-secret: ${NEXION_GATEWAY_INTERNAL_SECRET:nexion-local-gateway-secret}
  services:
    commerce-url: ${NEXION_COMMERCE_URL:http://localhost:8104}
