spring:
  application:
    name: nexion-system-service
  servlet:
    multipart:
      max-file-size: ${NEXION_SYSTEM_MULTIPART_MAX_FILE_SIZE:50MB}
      max-request-size: ${NEXION_SYSTEM_MULTIPART_MAX_REQUEST_SIZE:50MB}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:nexion}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: "${MYSQL_PASSWORD:A123456789Z!@#}"
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      username: "${SPRING_DATA_REDIS_USERNAME:}"
      password: "${SPRING_DATA_REDIS_PASSWORD:}"
  config:
    import:
      - optional:nacos:nexion-common.yaml
      - optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: "${NACOS_PASSWORD:nacos}"
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        file-extension: yaml

server:
  port: 8110
