package ffdd.opsconsole.finance.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public record WithdrawalOrderView(
        Long id,
        Long userId,
        String withdrawalNo,
        String asset,
        String chain,
        BigDecimal amount,
        BigDecimal fee,
        String targetAddress,
        Long riskDecisionId,
        String chainTxHash,
        String status,
        LocalDateTime chainSubmittedAt,
        LocalDateTime completedAt,
        LocalDateTime failedAt,
        String failureReason,
        Integer chainBroadcastAttempts,
        LocalDateTime nextBroadcastAt,
        String lastBroadcastError,
        LocalDateTime broadcastDeadAt,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        String userNo,
        String nickname,
        String phoneMasked,
        String kycStatus,
        String userStatus,
        Integer riskScore,
        String hitRules,
        String riskReason,
        Integer withdrawalCount24h,
        String statusHistory,
        String auditTrail,
        String userLevel,
        String deviceSummary,
        String referralPosition,
        String riskScoreBreakdown,
        String withdrawalHistory,
        BigDecimal penaltyFeeRate,
        BigDecimal grossFee,
        BigDecimal nexBurned,
        BigDecimal nexFeeOffsetRate,
        BigDecimal feeWaived,
        BigDecimal actualFee,
        BigDecimal netReceive,
        String ipSegment,
        LocalDateTime holdUntil,
        String lifecycleOwner,
        String freezePeriod,
        String previousStatus,
        String routingPriority,
        Integer k4BandLowMax,
        Integer k4BandHighMin,
        Integer k4AutoEscalateScore,
        String k3RiskRoute) {

    public WithdrawalOrderView(
            Long id,
            Long userId,
            String withdrawalNo,
            String asset,
            String chain,
            BigDecimal amount,
            BigDecimal fee,
            String targetAddress,
            Long riskDecisionId,
            String chainTxHash,
            String status,
            LocalDateTime chainSubmittedAt,
            LocalDateTime completedAt,
            LocalDateTime failedAt,
            String failureReason,
            Integer chainBroadcastAttempts,
            LocalDateTime nextBroadcastAt,
            String lastBroadcastError,
            LocalDateTime broadcastDeadAt,
            LocalDateTime createdAt,
            LocalDateTime updatedAt,
            String userNo,
            String nickname,
            String phoneMasked,
            String kycStatus,
            String userStatus,
            Integer riskScore,
            String hitRules,
            String riskReason,
            Integer withdrawalCount24h,
            String statusHistory,
            String auditTrail) {
        this(id, userId, withdrawalNo, asset, chain, amount, fee, targetAddress, riskDecisionId, chainTxHash,
                status, chainSubmittedAt, completedAt, failedAt, failureReason, chainBroadcastAttempts,
                nextBroadcastAt, lastBroadcastError, broadcastDeadAt, createdAt, updatedAt,
                userNo, nickname, phoneMasked, kycStatus, userStatus, riskScore, hitRules, riskReason,
                withdrawalCount24h, statusHistory, auditTrail,
                null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
                null, null, null, null, null);
    }

    public WithdrawalOrderView(
            Long id,
            Long userId,
            String withdrawalNo,
            String asset,
            String chain,
            BigDecimal amount,
            BigDecimal fee,
            String targetAddress,
            Long riskDecisionId,
            String chainTxHash,
            String status,
            LocalDateTime chainSubmittedAt,
            LocalDateTime completedAt,
            LocalDateTime failedAt,
            String failureReason,
            Integer chainBroadcastAttempts,
            LocalDateTime nextBroadcastAt,
            String lastBroadcastError,
            LocalDateTime broadcastDeadAt,
            LocalDateTime createdAt,
            LocalDateTime updatedAt) {
        this(id, userId, withdrawalNo, asset, chain, amount, fee, targetAddress, riskDecisionId, chainTxHash,
                status, chainSubmittedAt, completedAt, failedAt, failureReason, chainBroadcastAttempts,
                nextBroadcastAt, lastBroadcastError, broadcastDeadAt, createdAt, updatedAt,
                null, null, null, null, null, null, null, null, null, null, null,
                null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null,
                null, null, null, null, null);
    }
}
