USE nexion;

START TRANSACTION;

-- Physically remove menu records that are not present in the current PC left navigation.
CREATE TEMPORARY TABLE tmp_admin_menu_delete_ids AS
SELECT id
FROM admin_menu
WHERE menu_code LIKE 'MENU_%'
  AND menu_code NOT IN ('MENU_HOME', 'MENU_UMS', 'MENU_UMS_ADMIN', 'MENU_UMS_ROLE', 'MENU_UMS_MENU', 'MENU_UMS_PERMISSION', 'MENU_PLATFORM_BASE', 'MENU_PLATFORM_BASE_AUDIT', 'MENU_PLATFORM_BASE_APPROVALS', 'MENU_PLATFORM_BASE_SYSTEM', 'MENU_PLATFORM_BASE_EVENTS', 'MENU_PLATFORM_BASE_PHASE_CONFIG', 'MENU_DASHBOARD', 'MENU_DASHBOARD_COVERAGE', 'MENU_DASHBOARD_LIABILITY', 'MENU_DASHBOARD_FUNNEL', 'MENU_DASHBOARD_PHASE', 'MENU_DASHBOARD_RISK_RADAR', 'MENU_ACCOUNT', 'MENU_ACCOUNT_USERS', 'MENU_ACCOUNT_ACCOUNT_ACTIONS', 'MENU_ACCOUNT_ASSET_ADJUST', 'MENU_ACCOUNT_KYC', 'MENU_ACCOUNT_SESSIONS', 'MENU_ACCOUNT_AUTH_RISK', 'MENU_FINANCE', 'MENU_FINANCE_TOPUP', 'MENU_FINANCE_WITHDRAW', 'MENU_FINANCE_TREASURY', 'MENU_FINANCE_BILLS', 'MENU_FINANCE_WITHDRAW_CONFIG', 'MENU_DEVICE_COMMERCE', 'MENU_DEVICE_COMMERCE_SKU', 'MENU_DEVICE_COMMERCE_DEVICES', 'MENU_DEVICE_COMMERCE_GENERATION', 'MENU_DEVICE_COMMERCE_TASK_PRICING', 'MENU_DEVICE_COMMERCE_LIFECYCLE', 'MENU_DEVICE_COMMERCE_TRADEIN', 'MENU_DEVICE_COMMERCE_ORDERS', 'MENU_DISTRIBUTION_TEAM', 'MENU_DISTRIBUTION_TEAM_VRANK', 'MENU_DISTRIBUTION_TEAM_UNILEVEL', 'MENU_DISTRIBUTION_TEAM_BINARY', 'MENU_DISTRIBUTION_TEAM_LEADERSHIP', 'MENU_DISTRIBUTION_TEAM_COMMISSIONS', 'MENU_DISTRIBUTION_TEAM_QUOTA', 'MENU_DISTRIBUTION_TEAM_AGENT', 'MENU_DISTRIBUTION_TEAM_LEADERBOARD', 'MENU_FINANCIAL_PRODUCTS', 'MENU_FINANCIAL_PRODUCTS_STAKING', 'MENU_FINANCIAL_PRODUCTS_EXCHANGE', 'MENU_FINANCIAL_PRODUCTS_MARKET', 'MENU_FINANCIAL_PRODUCTS_GENESIS', 'MENU_FINANCIAL_PRODUCTS_PREMIUM', 'MENU_FINANCIAL_PRODUCTS_NEXV2', 'MENU_FINANCIAL_PRODUCTS_REINVEST', 'MENU_GROWTH', 'MENU_GROWTH_PHASE', 'MENU_GROWTH_TRIAL', 'MENU_GROWTH_QUEST', 'MENU_GROWTH_EVENTS', 'MENU_GROWTH_STREAK', 'MENU_GROWTH_MILESTONES', 'MENU_CMS', 'MENU_CMS_COPY', 'MENU_CMS_NOVA', 'MENU_CMS_NOTIFICATION', 'MENU_CMS_TRUST', 'MENU_CMS_DISCLOSURE', 'MENU_CMS_I18N', 'MENU_CMS_LEARN', 'MENU_EMERGENCY_CONTROL', 'MENU_EMERGENCY_CONTROL_KILLSWITCH', 'MENU_EMERGENCY_CONTROL_GEO', 'MENU_EMERGENCY_CONTROL_TAMPER', 'MENU_EMERGENCY_CONTROL_SOP', 'MENU_RISK_ANTI_CHEAT', 'MENU_RISK_ANTI_CHEAT_MULTI', 'MENU_RISK_ANTI_CHEAT_ARBITRAGE', 'MENU_RISK_ANTI_CHEAT_WITHDRAW_RULES', 'MENU_RISK_ANTI_CHEAT_SCORE', 'MENU_RISK_ANTI_CHEAT_KYC_REVIEW', 'MENU_BI', 'MENU_BI_KPI', 'MENU_BI_FUNNEL', 'MENU_BI_FINANCE', 'MENU_BI_OPS', 'MENU_BI_EXPORT');

DELETE rm
FROM admin_role_menu rm
JOIN tmp_admin_menu_delete_ids doomed ON doomed.id = rm.menu_id;

DELETE m
FROM admin_menu m
JOIN tmp_admin_menu_delete_ids doomed ON doomed.id = m.id;

DROP TEMPORARY TABLE tmp_admin_menu_delete_ids;

COMMIT;

SELECT COUNT(*) AS remaining_menu_count
FROM admin_menu
WHERE menu_code LIKE 'MENU_%';

SELECT id, menu_code, menu_name_zh, route_path, parent_id, sort_order, status, is_deleted
FROM admin_menu
WHERE menu_code LIKE 'MENU_%'
ORDER BY sort_order, id;
