USE nexion;

START TRANSACTION;

-- Physically remove menu records that are not present in the current PC left navigation from nexion-ops-console/lib/nav/console-nav.ts.
CREATE TEMPORARY TABLE tmp_admin_menu_delete_ids AS
SELECT id
FROM nx_admin_menu
WHERE menu_code LIKE 'MENU_%'
  AND menu_code NOT IN ('MENU_HOME', 'MENU_UMS', 'MENU_UMS_ADMIN', 'MENU_UMS_ROLE', 'MENU_UMS_MENU', 'MENU_UMS_PERMISSION', 'MENU_PLATFORM', 'MENU_PLATFORM_A1', 'MENU_PLATFORM_A2', 'MENU_PLATFORM_A3', 'MENU_PLATFORM_A4', 'MENU_PLATFORM_A5', 'MENU_OVERVIEW', 'MENU_OVERVIEW_B1', 'MENU_OVERVIEW_B2', 'MENU_OVERVIEW_B3', 'MENU_OVERVIEW_B4', 'MENU_OVERVIEW_B5', 'MENU_USERS', 'MENU_USERS_C1', 'MENU_USERS_C2', 'MENU_USERS_C3', 'MENU_USERS_C4', 'MENU_USERS_C5', 'MENU_USERS_C6', 'MENU_FINANCE', 'MENU_FINANCE_D1', 'MENU_FINANCE_D2', 'MENU_FINANCE_D3', 'MENU_FINANCE_D4', 'MENU_FINANCE_D5', 'MENU_DEVICES', 'MENU_DEVICES_E1', 'MENU_DEVICES_E2', 'MENU_DEVICES_E3', 'MENU_DEVICES_E4', 'MENU_DEVICES_E5', 'MENU_NETWORK', 'MENU_NETWORK_F1', 'MENU_NETWORK_F2', 'MENU_NETWORK_F3', 'MENU_NETWORK_F4', 'MENU_NETWORK_F5', 'MENU_FINANCE_PRODUCTS', 'MENU_FINANCE_PRODUCTS_G1', 'MENU_FINANCE_PRODUCTS_G2', 'MENU_FINANCE_PRODUCTS_G3', 'MENU_FINANCE_PRODUCTS_G4', 'MENU_FINANCE_PRODUCTS_G7', 'MENU_GROWTH', 'MENU_GROWTH_H1', 'MENU_GROWTH_H2', 'MENU_GROWTH_H3', 'MENU_GROWTH_H4', 'MENU_GROWTH_H5', 'MENU_GROWTH_H6', 'MENU_CONTENT', 'MENU_CONTENT_I1', 'MENU_CONTENT_I2', 'MENU_CONTENT_I3', 'MENU_CONTENT_I4', 'MENU_CONTENT_I5', 'MENU_CONTENT_I6', 'MENU_CONTENT_I7', 'MENU_EMERGENCY', 'MENU_EMERGENCY_J1', 'MENU_EMERGENCY_J2', 'MENU_EMERGENCY_J3', 'MENU_EMERGENCY_J4', 'MENU_RISK', 'MENU_RISK_K1', 'MENU_RISK_K2', 'MENU_RISK_K3', 'MENU_RISK_K4', 'MENU_RISK_K5', 'MENU_ANALYTICS', 'MENU_ANALYTICS_L1', 'MENU_ANALYTICS_L2', 'MENU_ANALYTICS_L3', 'MENU_ANALYTICS_L4', 'MENU_ANALYTICS_L5', 'MENU_SERVICE', 'MENU_SERVICE_M1', 'MENU_SERVICE_M2', 'MENU_SERVICE_M3', 'MENU_SERVICE_M4', 'MENU_SERVICE_M5');

DELETE rm
FROM nx_admin_role_menu rm
JOIN tmp_admin_menu_delete_ids doomed ON doomed.id = rm.menu_id;

DELETE m
FROM nx_admin_menu m
JOIN tmp_admin_menu_delete_ids doomed ON doomed.id = m.id;

DROP TEMPORARY TABLE tmp_admin_menu_delete_ids;

COMMIT;

SELECT COUNT(*) AS remaining_menu_count
FROM nx_admin_menu
WHERE menu_code LIKE 'MENU_%';

SELECT id, menu_code, menu_name_zh, route_path, parent_id, sort_order, status, is_deleted
FROM nx_admin_menu
WHERE menu_code LIKE 'MENU_%'
ORDER BY sort_order, id;
