INSERT INTO nx_config_item (id, config_key, config_value, value_type, config_group, visibility, remark, status)
VALUES
  (1801, 'profile.region.singapore.label', 'Singapore', 'STRING', 'profile', 'PUBLIC', 'App profile selectable region: Singapore.', 1),
  (1802, 'profile.region.hong_kong.label', 'Hong Kong', 'STRING', 'profile', 'PUBLIC', 'App profile selectable region: Hong Kong.', 1),
  (1803, 'profile.region.tokyo.label', 'Tokyo, JP', 'STRING', 'profile', 'PUBLIC', 'App profile selectable region: Tokyo.', 1),
  (1804, 'profile.region.seoul.label', 'Seoul, KR', 'STRING', 'profile', 'PUBLIC', 'App profile selectable region: Seoul.', 1),
  (1805, 'profile.region.berlin.label', 'Berlin, DE', 'STRING', 'profile', 'PUBLIC', 'App profile selectable region: Berlin.', 1),
  (1806, 'profile.region.london.label', 'London, UK', 'STRING', 'profile', 'PUBLIC', 'App profile selectable region: London.', 1),
  (1807, 'profile.region.dubai.label', 'Dubai, AE', 'STRING', 'profile', 'PUBLIC', 'App profile selectable region: Dubai.', 1),
  (1808, 'profile.region.new_york.label', 'New York, US', 'STRING', 'profile', 'PUBLIC', 'App profile selectable region: New York.', 1),
  (1809, 'profile.timezone.asia_singapore.label', 'Asia/Singapore (UTC+8)', 'STRING', 'profile', 'PUBLIC', 'App profile selectable timezone: Asia/Singapore.', 1),
  (1810, 'profile.timezone.asia_tokyo.label', 'Asia/Tokyo (UTC+9)', 'STRING', 'profile', 'PUBLIC', 'App profile selectable timezone: Asia/Tokyo.', 1),
  (1811, 'profile.timezone.asia_hong_kong.label', 'Asia/Hong_Kong (UTC+8)', 'STRING', 'profile', 'PUBLIC', 'App profile selectable timezone: Asia/Hong Kong.', 1),
  (1812, 'profile.timezone.europe_berlin.label', 'Europe/Berlin (UTC+1)', 'STRING', 'profile', 'PUBLIC', 'App profile selectable timezone: Europe/Berlin.', 1),
  (1813, 'profile.timezone.europe_london.label', 'Europe/London (UTC+0)', 'STRING', 'profile', 'PUBLIC', 'App profile selectable timezone: Europe/London.', 1),
  (1814, 'profile.timezone.asia_dubai.label', 'Asia/Dubai (UTC+4)', 'STRING', 'profile', 'PUBLIC', 'App profile selectable timezone: Asia/Dubai.', 1),
  (1815, 'profile.timezone.america_new_york.label', 'America/New_York (UTC-5)', 'STRING', 'profile', 'PUBLIC', 'App profile selectable timezone: America/New York.', 1),
  (1816, 'profile.avatar.mech_lime.accent', '#c6ff3a', 'STRING', 'profile', 'PUBLIC', 'App profile mechanical avatar lime accent color.', 1),
  (1817, 'profile.avatar.mech_lime.glow', 'rgba(198, 255, 58, 0.22)', 'STRING', 'profile', 'PUBLIC', 'App profile mechanical avatar lime glow color.', 1),
  (1818, 'profile.avatar.mech_cyan.accent', '#46e6ff', 'STRING', 'profile', 'PUBLIC', 'App profile mechanical avatar cyan accent color.', 1),
  (1819, 'profile.avatar.mech_cyan.glow', 'rgba(70, 230, 255, 0.2)', 'STRING', 'profile', 'PUBLIC', 'App profile mechanical avatar cyan glow color.', 1),
  (1820, 'profile.avatar.mech_violet.accent', '#b89cff', 'STRING', 'profile', 'PUBLIC', 'App profile mechanical avatar violet accent color.', 1),
  (1821, 'profile.avatar.mech_violet.glow', 'rgba(184, 156, 255, 0.22)', 'STRING', 'profile', 'PUBLIC', 'App profile mechanical avatar violet glow color.', 1),
  (1822, 'profile.avatar.mech_amber.accent', '#ffb84d', 'STRING', 'profile', 'PUBLIC', 'App profile mechanical avatar amber accent color.', 1),
  (1823, 'profile.avatar.mech_amber.glow', 'rgba(255, 184, 77, 0.22)', 'STRING', 'profile', 'PUBLIC', 'App profile mechanical avatar amber glow color.', 1),
  (1824, 'profile.avatar.mech_rose.accent', '#ff7896', 'STRING', 'profile', 'PUBLIC', 'App profile mechanical avatar rose accent color.', 1),
  (1825, 'profile.avatar.mech_rose.glow', 'rgba(255, 120, 150, 0.2)', 'STRING', 'profile', 'PUBLIC', 'App profile mechanical avatar rose glow color.', 1)
ON DUPLICATE KEY UPDATE
  config_value = VALUES(config_value),
  value_type = VALUES(value_type),
  config_group = VALUES(config_group),
  visibility = VALUES(visibility),
  remark = VALUES(remark),
  status = VALUES(status);
